name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
        
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.0
      with:
        cmdline-tools-version: 10406996
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.4.2
      with:
        ndk-version: 'r26b'
        link-to-sdk: true
        
    - name: Setup Go Mobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:$(go env GOPATH)/bin

    - name: Build
      run: |
        mkdir -p assets data
        bash gen_assets.sh download
        cp -v data/*.dat assets/
        gomobile init
        go mod tidy
        gomobile bind -v -androidapi 21 -ldflags='-s -w' ./

    - name: List built files
      run: |
        echo "=== Built files ==="
        find . -name "*.aar" -o -name "*.jar" | head -20

    - name: Create Release and Upload
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release  # ← TAMBAHKAN ID
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for ${{ github.ref_name }}
          
          Built from: ${{ github.sha }}
          
          **Download Links:**
          - AAR File: Will be available after upload
          - Sources JAR: Will be available after upload
        files: |
          ./*.aar
          ./*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Output Download URLs
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "🎉 Release created successfully!"
        echo "📦 Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
        echo ""
        echo "⬇️ Download Links:"
        echo "• AAR File: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/$(ls *.aar | head -1)"
        echo "• Sources JAR: https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/$(ls *.jar | head -1)"
        echo ""
        echo "🔗 Direct download URLs will be available once files are uploaded"
