name: Android Native Build

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'
  NDK_VERSION: '25.2.9519653'

jobs:
  build:
    name: Build Android Libraries
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.NDK_VERSION }}

    - name: Build for all architectures
      run: |
        chmod +x build_android.sh
        ./build_android.sh

    - name: Test library compatibility
      run: |
        for arch in arm64-v8a armeabi-v7a x86 x86_64; do
          if [ -f "dist/$arch/libv2ray.so" ]; then
            echo "Testing $arch..."
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf -l dist/$arch/libv2ray.so | grep "LOAD" || true
          fi
        done

    - name: Create build info
      run: |
        echo "Build Date: $(date)" > build-info.txt
        echo "Commit: ${{ github.sha }}" >> build-info.txt
        echo "Android NDK: ${{ env.NDK_VERSION }}" >> build-info.txt
        echo "Go Version: ${{ env.GO_VERSION }}" >> build-info.txt

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: android-libraries
        path: |
          dist/
          build-info.txt
        retention-days: 30

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/**/*.so
          build-info.txt
        draft: false
        prerelease: false
